language: php

sudo: true

php:
 - 7.1
 - 7.0

env:
 global:
  - MOODLE_BRANCH=MOODLE_36_STABLE
  - IGNORE_PATHS=screenshots
 matrix:
  - DB=pgsql
  - DB=mysqli

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat